{% set name = "pyaml-env" %}
{% set version = "1.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyaml_env-{{ version }}.tar.gz
  sha256: f83502516b6f1561ba7c2db9ced939a7a9933a66702d8071e98ad07da49a4bb4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - pyyaml >=5.0,<=7.0

test:
  imports:
    - pyaml_env
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/mkaranasou/pyaml_env
  summary: Provides yaml file parsing with environment variable resolution
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cburing
    - jan-janssen
