{% set name = "pyaml-env" %}
{% set version = "1.1.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyaml_env-{{ version }}.tar.gz
  sha256: b22179a96be995ef776364d7a22e84aba597d91f13b0cb797150e9ba047ea584

build:
  number: 0
  noarch: python
  script:
    - cp $RECIPE_DIR/requirements.txt .
    - {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - pyyaml ==5.4.1

test:
  imports:
    - pyaml_env
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mkaranasou/pyaml_env
  summary: Provides yaml file parsing with environment variable resolution
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cburing
